#########################################################################
# Title:            Community: Wireshark                                #
# Author(s):        Not@RealEmail                                       #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  ffeldhaus/wireshark                                 #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare-dns
  vars:
    record: shark
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: wireshark
    state: absent

- name: Create wireshark directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/wireshark

- name: Create and start container
  docker_container:
    name: wireshark
    image: ffeldhaus/wireshark
    pull: yes
    published_ports:
      - "127.0.0.1:14500:14500"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      VIRTUAL_HOST: "shark.{{ user.domain }}"
      VIRTUAL_PORT: "14500"
      LETSENCRYPT_HOST: "shark.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
    volumes:
      - "/opt/wireshark:/config"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - wireshark
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
